# Generated by Django 5.2.8 on 2026-08-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('BUS', 'Bus'), ('SELF_DRIVE', 'Self Drive')], default='CAR', max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL fallback')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats', models.IntegerField(default=5)),
                ('fuel', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('CNG', 'CNG')], default='PETROL', max_length=10)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=12)),
                ('ac', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=15)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
