# Generated by Django 5.2.8 on 2026-08-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Category specific details (JSON)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('JCB', 'JCB / Excavator'), ('TRACTOR', 'Tractor'), ('TRUCK', 'Truck'), ('MINI_TRUCK', 'Mini Truck'), ('TEMPO', 'Tempo / Goods Vehicle'), ('VAN', 'Van'), ('BUS', 'Bus'), ('CONSTRUCTION', 'Construction Equipment'), ('AGRICULTURAL', 'Agricultural Equipment'), ('OTHER', 'Other')], default='CAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
