# Generated by Django 5.2.8 on 2026-08-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_specifications_alter_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='locality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
