# Generated by Django 5.2.8 on 2026-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_rating_remove_vehicle_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='grace_period_minutes',
            field=models.IntegerField(default=60, help_text='Free grace period minutes for late returns'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='late_fee_per_hour',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Late fee charged per hour (rounded up) after grace period', max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='preparation_time_minutes',
            field=models.IntegerField(default=60, help_text='Turnaround minutes before vehicle is available again after return'),
        ),
    ]
