CATEGORY_CONFIG = {
    'CAR': {'label': 'Car', 'icon': 'Car', 'specs': [{'name': 'seats', 'label': 'Seats', 'type': 'number'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Petrol', 'Diesel', 'Electric', 'Hybrid', 'CNG']}, {'name': 'transmission', 'label': 'Transmission', 'type': 'select', 'options': ['Manual', 'Automatic']}]},
    'BIKE': {'label': 'Bike', 'icon': 'Bike', 'specs': [{'name': 'engine_cc', 'label': 'Engine CC', 'type': 'text'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Petrol', 'Electric']}, {'name': 'transmission', 'label': 'Transmission', 'type': 'select', 'options': ['Manual', 'Automatic']}]},
    'SCOOTER': {'label': 'Scooter', 'icon': 'Bike', 'specs': [{'name': 'engine_cc', 'label': 'Engine CC', 'type': 'text'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Petrol', 'Electric']}]},
    'JCB': {'label': 'JCB / Excavator', 'icon': 'Tractor', 'specs': [{'name': 'engine_power', 'label': 'Engine Power', 'type': 'text'}, {'name': 'operating_weight', 'label': 'Operating Weight (Tons)', 'type': 'number'}]},
    'TRACTOR': {'label': 'Tractor', 'icon': 'Tractor', 'specs': [{'name': 'horsepower', 'label': 'Horsepower (HP)', 'type': 'number'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Diesel']}, {'name': 'transmission', 'label': 'Transmission', 'type': 'select', 'options': ['Manual', 'Automatic']}]},
    'TRUCK': {'label': 'Truck', 'icon': 'Truck', 'specs': [{'name': 'load_capacity', 'label': 'Load Capacity (Tons)', 'type': 'number'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Diesel', 'CNG']}, {'name': 'vehicle_type', 'label': 'Vehicle Type', 'type': 'select', 'options': ['Open', 'Container']}]},
    'MINI_TRUCK': {'label': 'Mini Truck', 'icon': 'Truck', 'specs': [{'name': 'load_capacity', 'label': 'Load Capacity (Tons)', 'type': 'number'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Diesel', 'CNG']}]},
    'TEMPO': {'label': 'Tempo / Goods Vehicle', 'icon': 'Truck', 'specs': [{'name': 'load_capacity', 'label': 'Load Capacity (Tons)', 'type': 'number'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Diesel', 'CNG']}]},
    'VAN': {'label': 'Van', 'icon': 'Bus', 'specs': [{'name': 'seats', 'label': 'Seats', 'type': 'number'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Diesel', 'Petrol', 'CNG']}, {'name': 'ac', 'label': 'Air Conditioning', 'type': 'select', 'options': ['Yes', 'No']}]},
    'BUS': {'label': 'Bus', 'icon': 'Bus', 'specs': [{'name': 'seats', 'label': 'Seats', 'type': 'number'}, {'name': 'fuel', 'label': 'Fuel Type', 'type': 'select', 'options': ['Diesel', 'CNG']}, {'name': 'ac', 'label': 'Air Conditioning', 'type': 'select', 'options': ['Yes', 'No']}]},
    'CONSTRUCTION': {'label': 'Construction Equipment', 'icon': 'Tractor', 'specs': [{'name': 'equipment_type', 'label': 'Equipment Type', 'type': 'text'}, {'name': 'power', 'label': 'Power/Capacity', 'type': 'text'}]},
    'AGRICULTURAL': {'label': 'Agricultural Equipment', 'icon': 'Tractor', 'specs': [{'name': 'equipment_type', 'label': 'Equipment Type', 'type': 'text'}, {'name': 'power', 'label': 'Power/Capacity', 'type': 'text'}]},
    'OTHER': {'label': 'Other', 'icon': 'Car', 'specs': [{'name': 'description', 'label': 'Custom Specifications', 'type': 'text'}]},
}
CATEGORY_CHOICES = [(k, v['label']) for k, v in CATEGORY_CONFIG.items()]
